import type { CardSpine, DomainSpine } from './types';

// Lightweight content spine kept OUT of the heavy cards.ts/domains.ts chunks so
// the initial landing (Today/Blueprint) can compute due counts, coverage, and
// domain labels without pulling the full prose into the eager bundle. The full
// content stays single-sourced in cards.ts/domains.ts; content.test.ts asserts
// this spine never drifts from it.
export const cardIndex: CardSpine[] = [{"id":"d1-loop-stop","domainId":"d1","revision":1},{"id":"d1-orchestration","domainId":"d1","revision":1},{"id":"d1-task-agent","domainId":"d1","revision":1},{"id":"d1-hooks","domainId":"d1","revision":1},{"id":"d2-interface","domainId":"d2","revision":1},{"id":"d2-errors","domainId":"d2","revision":1},{"id":"d2-scope","domainId":"d2","revision":1},{"id":"d3-memory","domainId":"d3","revision":1},{"id":"d3-skills","domainId":"d3","revision":1},{"id":"d3-ci","domainId":"d3","revision":1},{"id":"d4-criteria","domainId":"d4","revision":1},{"id":"d4-schema","domainId":"d4","revision":1},{"id":"d4-retry","domainId":"d4","revision":1},{"id":"d5-context","domainId":"d5","revision":1},{"id":"d5-escalate","domainId":"d5","revision":1},{"id":"d5-provenance","domainId":"d5","revision":1},{"id":"d1-stop-truncation","domainId":"d1","revision":1},{"id":"d1-parallel-review","domainId":"d1","revision":1},{"id":"d1-subagent-input","domainId":"d1","revision":1},{"id":"d1-advisory-enforced","domainId":"d1","revision":1},{"id":"d1-hook-exit-codes","domainId":"d1","revision":1},{"id":"d1-fixed-vs-loop","domainId":"d1","revision":1},{"id":"d1-resume-vs-fork","domainId":"d1","revision":1},{"id":"d1-session-lookup","domainId":"d1","revision":1},{"id":"d2-description-depth","domainId":"d2","revision":1},{"id":"d2-consolidation","domainId":"d2","revision":1},{"id":"d2-error-channels","domainId":"d2","revision":1},{"id":"d2-tool-context","domainId":"d2","revision":1},{"id":"d2-config-scopes","domainId":"d2","revision":1},{"id":"d2-builtin-map","domainId":"d2","revision":1},{"id":"d2-act-verify","domainId":"d2","revision":1},{"id":"d3-file-locations","domainId":"d3","revision":1},{"id":"d3-trim-scope","domainId":"d3","revision":1},{"id":"d3-manual-skill","domainId":"d3","revision":1},{"id":"d3-plan-when","domainId":"d3","revision":1},{"id":"d3-reset-context","domainId":"d3","revision":1},{"id":"d3-verifiable-goal","domainId":"d3","revision":1},{"id":"d3-print-mode","domainId":"d3","revision":1},{"id":"d4-grader-choice","domainId":"d4","revision":1},{"id":"d4-example-quality","domainId":"d4","revision":1},{"id":"d4-output-vs-strict","domainId":"d4","revision":1},{"id":"d4-schema-gaps","domainId":"d4","revision":1},{"id":"d4-batch-shape","domainId":"d4","revision":1},{"id":"d4-batch-matching","domainId":"d4","revision":1},{"id":"d4-fresh-reviewer","domainId":"d4","revision":1},{"id":"d5-window-accounting","domainId":"d5","revision":1},{"id":"d5-approval-gaps","domainId":"d5","revision":1},{"id":"d5-actionable-errors","domainId":"d5","revision":1},{"id":"d5-scoped-reads","domainId":"d5","revision":1},{"id":"d5-research-isolation","domainId":"d5","revision":1},{"id":"d5-claim-shape","domainId":"d5","revision":1}];

export const domainIndex: DomainSpine[] = [{"id":"d1","number":1,"weight":27,"title":{"ja":"エージェント設計とオーケストレーション","en":"Agentic Architecture & Orchestration"}},{"id":"d2","number":2,"weight":18,"title":{"ja":"ツール設計とMCP統合","en":"Tool Design & MCP Integration"}},{"id":"d3","number":3,"weight":20,"title":{"ja":"Claude Code設定とワークフロー","en":"Claude Code Configuration & Workflows"}},{"id":"d4","number":4,"weight":20,"title":{"ja":"プロンプト設計と構造化出力","en":"Prompt Engineering & Structured Output"}},{"id":"d5","number":5,"weight":15,"title":{"ja":"コンテキスト管理と信頼性","en":"Context Management & Reliability"}}];
