import type { Domain, LocalizedText, Objective } from './types';
import { VERIFIED_AT } from './sources';

const localized = <T>(ja: T, en: T): LocalizedText<T> => ({ ja, en });

const objective = (
  id: string,
  title: LocalizedText,
  summary: LocalizedText,
  mustKnow: LocalizedText<string[]>,
  sourceIds: string[],
): Objective => ({
  id,
  title,
  summary,
  mustKnow,
  sourceIds: ['exam-guide', ...sourceIds],
  verifiedAt: VERIFIED_AT,
});

export const domains: Domain[] = [
  {
    id: 'd1',
    number: 1,
    title: localized('エージェント設計とオーケストレーション', 'Agentic Architecture & Orchestration'),
    weight: 27,
    summary: localized(
      'ツール実行ループ、委譲、状態管理を組み合わせ、止まり方まで説明できる設計を目指します。',
      'Design systems that combine tool-execution loops, delegation, and state management with explicit stopping behavior.',
    ),
    objectives: [
      objective(
        '1.1',
        localized('エージェントループ', 'Agentic loops'),
        localized('応答の停止理由に従って、ツール実行と次のモデル呼び出しを安全につなぐ。', 'Safely connect tool execution to the next model call based on the response stop reason.'),
        localized(['stop_reason を分岐条件にする', 'tool_result を会話履歴へ正しい順序で返す'], ['Use stop_reason as the branching condition', 'Return tool_result entries to the conversation history in the correct order']),
        ['stop-reasons', 'tool-use'],
      ),
      objective(
        '1.2',
        localized('マルチエージェント連携', 'Multi-agent orchestration'),
        localized('中央調整、引き継ぎ、並列化を依存関係と統合責任に合わせて選ぶ。', 'Choose centralized coordination, handoffs, or parallel execution based on dependencies and integration ownership.'),
        localized(['独立タスクだけを並列化する', '最終統合の所有者を明示する'], ['Parallelize only independent tasks', 'Name the owner of final integration']),
        ['sdk-features', 'subagents'],
      ),
      objective(
        '1.3',
        localized('サブエージェントの起動と文脈', 'Subagent invocation and context'),
        localized('子エージェントに必要十分な入力、出力形式、終了条件を渡す。', 'Give subagents sufficient input, an output format, and clear stopping conditions.'),
        localized(['親の文脈を暗黙に期待しない', 'Exam GuideのTask表記と現行DocsのAgent表記を区別する'], ['Do not assume the parent context is implicitly available', 'Distinguish the Exam Guide term “Task” from the current Docs term “Agent”']),
        ['subagents'],
      ),
      objective(
        '1.4',
        localized('ワークフロー強制と引き継ぎ', 'Workflow enforcement and handoffs'),
        localized('必須の業務ルールは文章によるお願いではなく、決定的な制御点で守る。', 'Enforce mandatory business rules at deterministic control points, not through prose requests alone.'),
        localized(['推奨と強制を区別する', '引き継ぎ時の必須データを構造化する'], ['Distinguish guidance from enforcement', 'Structure the required handoff data']),
        ['hooks', 'sdk-features'],
      ),
      objective(
        '1.5',
        localized('SDKフックとライフサイクル', 'SDK hooks and lifecycle triggers'),
        localized('処理の前後に観測・検証・遮断を差し込むフックの責任範囲を理解する。', 'Understand where hooks can observe, validate, and block operations across the lifecycle.'),
        localized(['適切なイベントを選ぶ', '終了コードと返却形式を確認する'], ['Choose the appropriate event', 'Verify exit codes and return formats']),
        ['hooks'],
      ),
      objective(
        '1.6',
        localized('固定・動的なタスク分解', 'Fixed vs dynamic task decomposition'),
        localized('予測可能な工程と、実行時に発見される工程を使い分けて分解する。', 'Decompose work differently for predictable steps and steps discovered at runtime.'),
        localized(['既知の手順は固定フローにする', '探索結果に依存する分岐は動的にする'], ['Use a fixed workflow for known steps', 'Make branches that depend on exploration results dynamic']),
        ['subagents', 'sdk-features'],
      ),
      objective(
        '1.7',
        localized('セッション状態・再開・分岐', 'Session state, resume and fork'),
        localized('継続、再開、別案の分岐で、どの履歴と識別子を引き継ぐかを設計する。', 'Decide which history and identifiers carry over when continuing, resuming, or forking a session.'),
        localized(['重要な状態を会話だけに埋めない', '再開と分岐の目的を区別する'], ['Do not bury important state only in the conversation', 'Distinguish the purposes of resuming and forking']),
        ['sessions'],
      ),
    ],
  },
  {
    id: 'd2',
    number: 2,
    title: localized('ツール設計とMCP統合', 'Tool Design & MCP Integration'),
    weight: 18,
    summary: localized(
      'モデルが選びやすく、呼び間違えにくく、失敗から回復できるツール境界を設計します。',
      'Design tool boundaries that are easy for models to select, hard to misuse, and able to support recovery from failure.',
    ),
    objectives: [
      objective(
        '2.1',
        localized('有効なツール境界', 'Effective tool interfaces and boundaries'),
        localized('名前、説明、入力スキーマを、モデルが選択判断に使える契約として設計する。', 'Design names, descriptions, and input schemas as contracts the model can use to choose tools.'),
        localized(['曖昧な万能ツールを避ける', '入力制約と利用境界を明記する'], ['Avoid ambiguous, all-purpose tools', 'State input constraints and usage boundaries']),
        ['tool-use', 'mcp-tools'],
      ),
      objective(
        '2.2',
        localized('構造化されたツールエラー', 'Structured tool and MCP errors'),
        localized('失敗の種類、再試行可否、次の行動に必要な情報を機械可読で返す。', 'Return the failure type, retryability, and information needed for the next action in a machine-readable form.'),
        localized(['一時障害と恒久障害を分ける', '秘密や内部詳細を漏らさない'], ['Distinguish transient from permanent failures', 'Do not expose secrets or internal details']),
        ['mcp-tools', 'tool-use'],
      ),
      objective(
        '2.3',
        localized('ツールの配分・数・選択', 'Tool distribution, count and choice'),
        localized('責任と利用場面でツールをまとめ、不要な選択肢を同時に見せない。', 'Group tools by responsibility and use case, and avoid presenting unnecessary choices at the same time.'),
        localized(['専門エージェントへの配分を検討する', '分割し過ぎによる往復も評価する'], ['Consider assigning tools to specialized agents', 'Account for extra round trips caused by over-fragmentation']),
        ['sdk-features', 'tool-use'],
      ),
      objective(
        '2.4',
        localized('MCPサーバー統合とスコープ', 'MCP server integration and scope'),
        localized('MCPの接続設定、公開範囲、資格情報の境界を環境ごとに管理する。', 'Manage MCP connection settings, exposure scope, and credential boundaries for each environment.'),
        localized(['秘密情報を設定ファイルへ直書きしない', 'ユーザー・プロジェクト等のスコープを選ぶ'], ['Do not hard-code secrets in configuration files', 'Choose an appropriate scope, such as user or project']),
        ['mcp-tools', 'code-mcp'],
      ),
      objective(
        '2.5',
        localized('組み込みツールの責任', 'Built-in tool responsibilities'),
        localized('読取、検索、編集、コマンド実行の役割とリスクに応じて道具を選ぶ。', 'Choose tools according to the roles and risks of reading, searching, editing, and executing commands.'),
        localized(['探索は狭い検索から始める', '変更前に対象を読み、変更後に検証する'], ['Begin exploration with a narrow search', 'Read the target before changing it and verify afterward']),
        ['code-how'],
      ),
    ],
  },
  {
    id: 'd3',
    number: 3,
    title: localized('Claude Code設定とワークフロー', 'Claude Code Configuration & Workflows'),
    weight: 20,
    summary: localized(
      '指示の配置、再利用可能な手順、非対話実行をチームで保守できる形にします。',
      'Organize instructions, reusable procedures, and non-interactive execution so a team can maintain them.',
    ),
    objectives: [
      objective(
        '3.1',
        localized('CLAUDE.mdの階層', 'CLAUDE.md hierarchy'),
        localized('共有指示、個人指示、ディレクトリ固有の指示を適切な層へ置く。', 'Place shared, personal, and directory-specific instructions at the appropriate level.'),
        localized(['適用範囲と優先関係を確認する', '共有すべき指示はバージョン管理する'], ['Check scope and precedence', 'Version-control instructions that should be shared']),
        ['code-memory'],
      ),
      objective(
        '3.2',
        localized('コマンドとSkills', 'Commands vs Skills'),
        localized('明示的に呼ぶ定型操作と、必要に応じて利用される再利用知識を使い分ける。', 'Distinguish explicitly invoked routine operations from reusable knowledge loaded when needed.'),
        localized(['利用者が起動する操作を見分ける', '説明文と参照資源を小さく保つ'], ['Identify operations initiated by the user', 'Keep descriptions and reference resources focused']),
        ['skills', 'code-features'],
      ),
      objective(
        '3.3',
        localized('パス固有ルールとglob', 'Path-specific rules and globs'),
        localized('ファイル種別や場所にだけ必要な指示をglobで限定する。', 'Use globs to limit instructions to the file types or locations that need them.'),
        localized(['globが意図したファイルに一致するか検証する', '全体指示との重複を避ける'], ['Verify that the glob matches the intended files', 'Avoid duplicating global instructions']),
        ['code-memory'],
      ),
      objective(
        '3.4',
        localized('Plan modeと探索', 'Plan mode and exploration'),
        localized('大きな変更では実装前に依存関係、変更範囲、検証方法を整理する。', 'For substantial changes, map dependencies, scope, and verification before implementation.'),
        localized(['読取と設計の段階を分ける', '単純作業には過剰適用しない'], ['Separate the reading and design phases', 'Do not over-apply this process to simple work']),
        ['code-best-practices'],
      ),
      objective(
        '3.5',
        localized('反復改善と例示', 'Iterative refinement and examples'),
        localized('初稿、評価、修正の短いループで、具体例を基準に品質を上げる。', 'Improve quality through short draft, evaluation, and revision loops grounded in concrete examples.'),
        localized(['評価基準を先に決める', '修正ごとに回帰を確認する'], ['Define evaluation criteria first', 'Check for regressions after each revision']),
        ['code-best-practices', 'prompting-best'],
      ),
      objective(
        '3.6',
        localized('CI/CD・非対話統合', 'CI/CD and non-interactive integration'),
        localized('人の入力を待たない実行方式で、権限、終了状態、出力形式を固定する。', 'Use non-interactive execution with fixed permissions, exit behavior, and output formats.'),
        localized(['最小権限で動かす', '失敗をCIが判定できる形で返す'], ['Run with least privilege', 'Report failures in a form CI can evaluate']),
        ['headless'],
      ),
    ],
  },
  {
    id: 'd4',
    number: 4,
    title: localized('プロンプト設計と構造化出力', 'Prompt Engineering & Structured Output'),
    weight: 20,
    summary: localized(
      '評価基準とスキーマを明示し、検証可能な出力へ段階的に導きます。',
      'Make evaluation criteria and schemas explicit, then guide generation toward verifiable output in stages.',
    ),
    objectives: [
      objective(
        '4.1',
        localized('明示的なレビュー基準', 'Explicit review criteria'),
        localized('良い結果の条件を観察可能な項目に分解し、評価のぶれを減らす。', 'Break the conditions for a good result into observable criteria to reduce evaluation variance.'),
        localized(['曖昧な「高品質」を具体化する', '合否または尺度を定義する'], ['Turn vague notions of “high quality” into concrete criteria', 'Define pass/fail conditions or a scale']),
        ['evals'],
      ),
      objective(
        '4.2',
        localized('Few-shotと例示', 'Few-shot examples'),
        localized('望む入出力の対応例で、曖昧な規則や境界例を具体化する。', 'Clarify ambiguous rules and edge cases with examples of the desired input-output mapping.'),
        localized(['代表例と境界例を選ぶ', '例と指示が矛盾しないようにする'], ['Choose representative examples and edge cases', 'Ensure examples do not contradict the instructions']),
        ['prompting-best'],
      ),
      objective(
        '4.3',
        localized('構造化出力とスキーマ', 'Structured outputs and schemas'),
        localized('JSON Schemaにより型と必須項目を定義し、後段が扱える形を保証する。', 'Use JSON Schema to define types and required fields so downstream systems receive a usable structure.'),
        localized(['構文保証と意味妥当性を区別する', '過度に複雑なスキーマを避ける'], ['Distinguish structural guarantees from semantic validity', 'Avoid overly complex schemas']),
        ['structured'],
      ),
      objective(
        '4.4',
        localized('検証と再試行', 'Validation and retry'),
        localized('出力を検証し、具体的な不一致をフィードバックして限定的に再試行する。', 'Validate output and retry within limits using specific mismatches as feedback.'),
        localized(['失敗箇所を明示して返す', '上限とフォールバックを設ける'], ['Report the exact point of failure', 'Set retry limits and a fallback']),
        ['structured', 'evals'],
      ),
      objective(
        '4.5',
        localized('バッチ処理', 'Batch processing'),
        localized('即時応答が不要な大量処理を非同期化し、個別結果と失敗を追跡する。', 'Process high-volume work asynchronously when immediate responses are unnecessary, tracking each result and failure.'),
        localized(['待ち時間の許容可否で選ぶ', 'リクエストIDと結果を対応付ける'], ['Choose based on whether latency is acceptable', 'Associate each request ID with its result']),
        ['batch'],
      ),
      objective(
        '4.6',
        localized('複数パスのレビュー', 'Multi-pass review'),
        localized('生成、局所評価、全体統合を分け、各パスの役割を明確にする。', 'Separate generation, focused evaluation, and final integration, with a clear role for each pass.'),
        localized(['一度の巨大プロンプトに詰め込まない', '統合時に全体整合を再確認する'], ['Do not pack everything into one enormous prompt', 'Recheck global consistency during integration']),
        ['evals', 'subagents'],
      ),
    ],
  },
  {
    id: 'd5',
    number: 5,
    title: localized('コンテキスト管理と信頼性', 'Context Management & Reliability'),
    weight: 15,
    summary: localized(
      '長い処理でも重要事実、失敗理由、根拠を失わず、人に渡す境界を決めます。',
      'Preserve critical facts, failure reasons, and evidence during long-running work, and define when to hand control to a person.',
    ),
    objectives: [
      objective(
        '5.1',
        localized('コンテキストの保持', 'Preserve context'),
        localized('長い履歴を圧縮しつつ、識別子や決定事項などの重要事実を別に保持する。', 'Compress long histories while preserving identifiers, decisions, and other critical facts separately.'),
        localized(['要約で失ってはいけない事実を分離する', '再開に必要な状態を明示する'], ['Separate facts that must survive summarization', 'Make the state required for resumption explicit']),
        ['context-windows', 'context-editing'],
      ),
      objective(
        '5.2',
        localized('エスカレーションと曖昧さ', 'Escalation and ambiguity'),
        localized('権限不足、高リスク、解消不能な曖昧さを、人へ渡す明確な条件にする。', 'Define clear handoff conditions for insufficient permissions, high risk, or ambiguity that cannot be resolved.'),
        localized(['自己申告の自信だけに頼らない', '必要な文脈を添えて引き継ぐ'], ['Do not rely only on self-reported confidence', 'Include the necessary context in the handoff']),
        ['user-input'],
      ),
      objective(
        '5.3',
        localized('エラー伝播と回復', 'Error propagation and recovery'),
        localized('下流の失敗を分類し、試行内容と部分結果を上流が判断できる形で返す。', 'Classify downstream failures and return attempts and partial results in a form the caller can evaluate.'),
        localized(['元の原因を失わない', '再試行可能性と代替案を示す'], ['Preserve the original cause', 'Indicate retryability and alternatives']),
        ['tool-use', 'mcp-tools'],
      ),
      objective(
        '5.4',
        localized('コードベース探索', 'Codebase exploration'),
        localized('検索、読取、依存関係の追跡を狭い仮説から広げ、変更前に構造を把握する。', 'Expand searches, reads, and dependency tracing from a narrow hypothesis to understand the structure before changing it.'),
        localized(['ファイル名検索と内容検索を使い分ける', '推測を実ファイルで検証する'], ['Use filename and content searches appropriately', 'Verify assumptions against actual files']),
        ['large-codebases'],
      ),
      objective(
        '5.5',
        localized('人によるレビュー', 'Human review'),
        localized('重大度、カテゴリ、例外条件に応じて人の確認を組み込み、結果を測る。', 'Add human review based on severity, category, and exception conditions, then measure the results.'),
        localized(['全体平均だけでなく分類別に見る', 'レビュー結果を改善ループへ戻す'], ['Evaluate by category, not only by the overall average', 'Feed review results back into the improvement loop']),
        ['evals', 'user-input'],
      ),
      objective(
        '5.6',
        localized('来歴と出典対応', 'Provenance and source attribution'),
        localized('主張と根拠の対応を生成から統合まで保持し、後から追跡できるようにする。', 'Preserve claim-to-evidence mappings from generation through integration so they remain traceable.'),
        localized(['出典IDを構造化して運ぶ', '統合時に出典対応を落とさない'], ['Carry source IDs in a structured form', 'Preserve source mappings during integration']),
        ['structured'],
      ),
    ],
  },
];
